<?php
$tuefind = $this->tuefind();
$currentSystem = $tuefind->getTueFindType();
$publicationEmail = $tuefind->getPublicationEmail();
?>

Gentile Utente,

Lei ha fatto richiesta di accesso al suo ID di Autrice/Autore in <?=$currentSystem?>. Esso è stato approvato.

Ora può depositare in forma digitale le pubblicazioni collegate al suo ID.

Una volta avvenuto il login mediante il suo account personale in <?=$currentSystem?>, apparirà in correlazione alle sue pubblicazioni il bottone digitale “republish”.

Cliccando su di esso, può caricare il relativo full text in formato PDF. Al termine del caricamento viene attribuito al documento digitale un link duraturo (handle/doi) ed il suo contributo è disponibile in Open Access all’intera utenza.

Se desidera caricare anche publicazioni non ancora presenti in <?=$currentSystem?>, la preghiamo di contattarci (<?=$publicationEmail?>). Qualora non dovesse essere possibile caricare contributi presenti in IxTheo, ci contatti pure.

Rimanendo a sua disposizione per ogni eventuale chiarimento 

Con i migliori saluti 

<?=$currentSystem?> Team
