<div class="panel panel-top panel-default tf-panel-home-3">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('Cuneiform_inscriptions_from_Persepolis_by_Nickmard_Khoey.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>OCB Services</h4>
        <p>
            <ul>
                <li>Dienst 1</li>
                <li>Dienst 2</li>
                <li>Dienst 3</li>
            </ul>
        </p>
    </div>
</div>
