<div id="searchbox_news">
    <h2><?=$this->transEsc('RelBib News')?></h2>
    <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#02_2023"><b>RelBib LunchTalk "Open Access publizieren – Allgemeine Informationen und Angebote des FID Religionswissenschaft" am 22.03.2023</b></a></li>
		<li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#05_2022"><b>Nationallizenz für World Religion Database (WRD) verfügbar!</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#12_2021"><b>Neu in RelBib: Normdatensuche und Personenseiten</b></a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">Archiv</a>
</div>
