<div class="panel panel-top panel-default tf-panel-home-3">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('220px-UnicornNiebuhr.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>OCB...</h4>
        <p>
            <ul>
                <li>Bullet 1</li>
                <li>Bullet 2</li>
                <li>Bullet 3</li>
                <li>Bullet 4</li>
            </ul>
        </p>
    </div>
</div>
