<div id="about_keibi">
    <div class="panel-body" style="font-size: 130%; text-align: justify">
    <p>The International Cuneiform Bibliography (Internationale Keilschriftbibliography - KeiBi) published in the journal Orientalia which is issued by the Papal Bible Institute since 1940, has become an indepensible aid for in research teaching and study of ancient near eastern studies. However, as in all printed bibliographies published over a long period of time, finding information in it is a tedious task. To ease the access the data of KeiBi the KeiBi data is integrated into a database which allows to search all volumes in parallel.
    <p>KeiBi was facilitated by the Deutsche Forschungsgemeinschaft (DFG) and the creation was supported by the Virtuelle Fachbibliothek Altertumswissenschaften „Propylaeum“. The KeiBi database was developed as part of the Propyleum Module Ancient  at the University Library of Tübingen with the support of the Institute for Ancient Near Eastern Studies (IANES).
       <p>The KeiBi data is provided as part of a cooperation with the Institut für Altorientalische Philologie und Vorderasiatische Altertumskunde der Universität Münster by the current creator of the bibliography, Prof. Dr. Hans Neumann. The volumes are scanned and preprocessed for digital presentation.
    </div>
</div>
