<?php if ($this->accountCapabilities()->getPublicationSetting() === 'enabled'):
  $routeParams = $this->tuefind()->getRouteParams();
  $recordId = $routeParams['id'];
  $config = $this->tuefind()->getConfig('tuefind');
  $publication = $this->tuefind()->getPublicationByControlNumber($recordId);
  $authorsIds = $this->driver->getPrimaryAuthorsIds();
  $showPublishButton = $this->tuefind()->getUserAccessPublishButton($authorsIds);
  $authors = $this->driver->getDeduplicatedAuthors();
  $showDspaceLink = false;
  $showPublicationLink = false;
  if (isset($publication)) {
    $showPublicationLink = true;
    $dspaceServer = $config->Publication->dspace_url_base;
    if(!strpos($publication->external_document_id, '/')) {
      $dspaceLink = $dspaceServer."/items/".$publication->external_document_guid;
    }else{
      $dspaceLink = $dspaceServer."/xmlui/handle/".$publication->external_document_id;
    }
  }?>

  <li>
    <?php if($showPublicationLink):?>
      <a class="toolbar-btn btn-type-publish" target="_blank" href="<?=$dspaceLink;?>"><?=$this->transEsc('publication_file_button')?></a>
    <?php elseif($showPublishButton): ?>
      <a class="toolbar-btn btn-type-publish" href="<?=$this->url('myresearch-publish', ['record_id' => $recordId])?>"><?=$this->transEsc('publication_request_button')?></a>
    <?php else:?>
      <a class="toolbar-btn btn-type-publish" data-lightbox href="<?=$this->url('help-home')?>?topic=publication" rel="nofollow"><?=$this->transEsc('publication_request_button')?></a>
    <?php endif; ?>
  </li>
<?php endif;?>
