<?php
$tuefind = $this->tuefind();
$currentSystem = $tuefind->getTueFindType();
$publicationEmail = $tuefind->getPublicationEmail();
?>

Dear <?=$currentSystem?> user,

You have requested access rights to your author ID in <?=$currentSystem?>. Your request was approved. You can now republish articles and essays linked to your author ID.

When you log into your <?=$currentSystem?> account, you will see the button labelled “republish” for articles linked to your author ID.

When you click on “republish”, you will be able to upload your article as a PDF-file. This file will then receive a permanent link (handle/doi) and be made available to other users in Open Access.

If you would like to upload articles which aren’t already in our catalogue, if you’re having trouble uploading a file, or for any other question, please contact us (<?=$publicationEmail?>).

Best regards,

Your <?=$currentSystem?>-Team