################################################################################
# marc_ixtheo.properties -- IxTheo overrides to standard TueFind mappings.     #
#                           All settings in this file override equivalent      #
#                           settings in marc.properties.                       #
#                           This file will be merged with                      #
#                           marc_tuefind.properties                            #
################################################################################

# VuFind overrides - Only IxTheo
era_facet = custom(org.tuefind.index.TueFindBiblio), getValuesOrUnassigned(610y:611y:630y:648a:648y:650y:651y:655y:689d)
geographic_facet = custom(org.tuefind.index.TueFindBiblio), getRegionTranslated(600z:610z:611z:630z:648z:650z:651a:651z:655z:689abctnp, "$p. :$n :$x|: ", "de")
issn = 022a:029a:440x:490x:730x:773x:776x:780x:785x
physical = custom(org.tuefind.index.TueFindBiblio), getPhysicalType
publisher = custom(org.tuefind.index.IxTheoPublisherTools), getNormalizedPublishers
topic_facet = custom(org.tuefind.index.TueFindBiblio), getTopicFacetTranslated(600a:600x:610a:610x:611a:611x:630a:630x:648a:648x:650a:650x:651a:651x:655a:655x:689abctnpz, "$p. :$n :$x|||:$z[()]: ", "de")

# additional custom fields - Only IxTheo (see schema_ixtheo_fields.xml)
author_synonyms = 109a
corporation = 110abg:111ab:710ab:711ab, first
last_indexed = custom, getLastIndexed(001)
last_modification_time = custom(org.tuefind.index.TueFindBiblio), getLastModificationTime
other_titles = custom(org.tuefind.index.TueFindBiblio), getOtherTitles
publisher_facet = custom(org.tuefind.index.IxTheoPublisherTools), getPublishersOrUnassigned
recording_date = custom(org.tuefind.index.TueFindBiblio), getRecordingDate
subsystem = SUBa
title_keywords = 601a
topic_de = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "", "de")
topic_en = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "", "en")
topic_es = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "", "es")
topic_fr = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "", "fr")
topic_hans = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "", "hans")
topic_hant = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "", "hant")
topic_it = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "", "it")
topic_pt = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "", "pt")
topic_ru = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "", "ru")
topic_el = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "", "el")
topic_facet_de = custom(org.tuefind.index.TueFindBiblio), getTopicFacetTranslated(600a:600x:610a:610x:611a:611x:630a:630x:648a:648x:650a:650x:651az:651x:655x:689abctnpz, "$p. :$n :$x|||:$z[()]: ", "de")
topic_facet_en = custom(org.tuefind.index.TueFindBiblio), getTopicFacetTranslated(600a:600x:610a:610x:611a:611x:630a:630x:648a:648x:650a:650x:651az:651x:655x:689abctnpz, "$p. :$n :$x|||:$z[()]: ", "en")
topic_facet_es = custom(org.tuefind.index.TueFindBiblio), getTopicFacetTranslated(600a:600x:610a:610x:611a:611x:630a:630x:648a:648x:650a:650x:651az:651x:655x:689abctnpz, "$p. :$n :$x|||:$z[()]: ", "es")
topic_facet_fr = custom(org.tuefind.index.TueFindBiblio), getTopicFacetTranslated(600a:600x:610a:610x:611a:611x:630a:630x:648a:648x:650a:650x:651az:651x:655x:689abctnpz, "$p. :$n :$x|||:$z[()]: ", "fr")
topic_facet_hans = custom(org.tuefind.index.TueFindBiblio), getTopicFacetTranslated(600a:600x:610a:610x:611a:611x:630a:630x:648a:648x:650a:650x:651az:651x:655x:689abctnpz, "$p. :$n :$x|||:$z[()]: ", "hans")
topic_facet_hant = custom(org.tuefind.index.TueFindBiblio), getTopicFacetTranslated(600a:600x:610a:610x:611a:611x:630a:630x:648a:648x:650a:650x:651az:651x:655x:689abctnpz, "$p. :$n :$x|||:$z[()]: ", "hant")
topic_facet_it = custom(org.tuefind.index.TueFindBiblio), getTopicFacetTranslated(600a:600x:610a:610x:611a:611x:630a:630x:648a:648x:650a:650x:651az:651x:655x:689abctnpz, "$p. :$n :$x|||:$z[()]: ", "it")
topic_facet_pt = custom(org.tuefind.index.TueFindBiblio), getTopicFacetTranslated(600a:600x:610a:610x:611a:611x:630a:630x:648a:648x:650a:650x:651az:651x:655x:689abctnpz, "$p. :$n :$x|||:$z[()]: ", "pt")
topic_facet_ru = custom(org.tuefind.index.TueFindBiblio), getTopicFacetTranslated(600a:600x:610a:610x:611a:611x:630a:630x:648a:648x:650a:650x:651az:651x:655x:689abctnpz, "$p. :$n :$x|||:$z[()]: ", "ru")
topic_facet_el = custom(org.tuefind.index.TueFindBiblio), getTopicFacetTranslated(600a:600x:610a:610x:611a:611x:630a:630x:648a:648x:650a:650x:651az:651x:655x:689abctnpz, "$p. :$n :$x|||:$z[()]: ", "el")
topic_non_standardized_de = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "$p. :$n :$x|:$z[()]: ", "de")
topic_non_standardized_en = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "$p. :$n :$x|:$z[()]: ", "en")
topic_non_standardized_es = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "$p. :$n :$x|:$z[()]: ", "es")
topic_non_standardized_fr = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "$p. :$n :$x|:$z[()]: ", "fr")
topic_non_standardized_hans = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "$p. :$n :$x|:$z[()]: ", "hans")
topic_non_standardized_hant = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "$p. :$n :$x|:$z[()]: ", "hant")
topic_non_standardized_it = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "$p. :$n :$x|:$z[()]: ", "it")
topic_non_standardized_pt = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "$p. :$n :$x|:$z[()]: ", "pt")
topic_non_standardized_ru = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "$p. :$n :$x|:$z[()]: ", "ru")
topic_non_standardized_el = custom(org.tuefind.index.TueFindBiblio), getTopics(600:610:630:648:650:651:653:655, "$p. :$n :$x|:$z[()]: ", "el")
topic_standardized_de = custom(org.tuefind.index.IxTheoKeywordChains), getKeyWordChain(689, "de")
topic_standardized_en = custom(org.tuefind.index.IxTheoKeywordChains), getKeyWordChain(689, "en")
topic_standardized_es = custom(org.tuefind.index.IxTheoKeywordChains), getKeyWordChain(689, "es")
topic_standardized_fr = custom(org.tuefind.index.IxTheoKeywordChains), getKeyWordChain(689, "fr")
topic_standardized_hans = custom(org.tuefind.index.IxTheoKeywordChains), getKeyWordChain(689, "hans")
topic_standardized_hant = custom(org.tuefind.index.IxTheoKeywordChains), getKeyWordChain(689, "hant")
topic_standardized_it = custom(org.tuefind.index.IxTheoKeywordChains), getKeyWordChain(689, "it")
topic_standardized_pt = custom(org.tuefind.index.IxTheoKeywordChains), getKeyWordChain(689, "pt")
topic_standardized_ru = custom(org.tuefind.index.IxTheoKeywordChains), getKeyWordChain(689, "ru")
topic_standardized_el = custom(org.tuefind.index.IxTheoKeywordChains), getKeyWordChain(689, "el")
topic_synonyms = custom(org.tuefind.index.IxTheoBiblio), getBCENormalizedContents(SYAa:SYBa:SYCa:SYDa:SYEa:SYFa:SYGa:STAa:STBa:STCa:STDa:STEa:STFa:STGa:STHa:STIa:REFa)
types_and_persistent_identifiers = custom(org.tuefind.index.TueFindBiblio), getTypesAndPersistentIdentifiers
keibi_internal = KEIa
keibi_reviews = REVa
keibi_volume = VOLa
journal_issue = custom(org.tuefind.index.OCBBiblio), getJournalIssue
language = 041a, language_map.properties
