<style>
    .read-more-state ~ .read-more-trigger:before {
        content: 'Show more';
    }

    .read-more-state:checked ~ .read-more-trigger:before {
        content: 'Show less';
    }
</style>
<div id="searchbox_news">
    <div id="0" class="panel-collapse" >
        <div class="panel-body" style="text-align: justify">
        <input type="checkbox" class="read-more-state" style="border: 5px solid #000;" id="post-1" />
                    <div class="read-more-wrap">
        <p>For technical reasons the former version of <strong>KeiBi</strong> from 2012 had to be shut down. Based on the data of the latest version and as a prototype of a planned more comprehensive project called <strong>Online Cuneiform Bibliography (OCB)</strong> that evaluates additional sources we present <strong>KeiBi (new)</strong>. The current version is based on the bibliographic search system VuFind.
        <div class="read-more-target">
        <p>The International Cuneiform Bibliography (Internationale Keilschriftbibliography - KeiBi) published in the journal Orientalia which is issued by the Papal Bible Institute since 1940, has become an indepensible aid for in research teaching and study of ancient near eastern studies. However, as in all printed bibliographies published over a long period of time, finding information in it is a tedious task. To ease the access the data of KeiBi the KeiBi data is integrated into a database which allows to search all volumes in parallel.
        <p>KeiBi was facilitated by the Deutsche Forschungsgemeinschaft (DFG) and the creation was supported by the Virtuelle Fachbibliothek Altertumswissenschaften „Propylaeum“. The KeiBi database was developed as part of the Propyleum Module Ancient  at the University Library of Tübingen with the support of the Institute for Ancient Near Eastern Studies (IANES).
        <p>The KeiBi data is provided as part of a cooperation with the Institut für Altorientalische Philologie und Vorderasiatische Altertumskunde der Universität Münster by the current creator of the bibliography, Prof. Dr. Hans Neumann. The volumes are scanned and preprocessed for digital presentation.
        </div>
    </div>
    <label for="post-1" class="read-more-trigger" style="border-color : #888"></label>
</div>
