<ul class="nav nav-pills">
    <li>
        <a href="<?=$this->advSearchUrl . ((isset($this->searchId) && $this->searchId) ? '?edit=' . $this->escapeHtmlAttr($this->searchId) : $this->hiddenFilterParams)?>"
           class="btn btn-link" role="button"
           rel="nofollow"><?= $this->transEsc("Advanced Search") ?></a>
    </li>

    <li>
        <a href="<?=$this->url('search-history')?>"
           class="btn btn-light" role="button"
           rel="nofollow"><?=$this->transEsc('Search History')?></a>
    </li>

    <li>
        <a href="<?=$this->url('help-home')?>?topic=search"
           class="btn btn-light" role="button" data-lightbox=""
           rel="nofollow"><?= $this->transEsc('Search Tips') ?></a>
    </li>
</ul>
