<div class="title">
    <div id="ocb-title-table">
        <div id="ocb-title-table-left">
        <a href=<?=$this->url('home')?>>
                <font id="ocb-logo-left">KeiBi online</font>
            </a>
        </div>
        <div id="ocb-title-table-right">
            <div id="ocb-logo-right"><?=$this->transEsc("Die Keilschrift-Bibliographie im Netz")?></div>
        </div>
    </div>
</div>
