<h1>FID-Lizenz: Zugriff mit RelBib-Konto</h1>
<?php if ($locked): ?>
  <h2><?=$this->transEsc('access_denied')?></h2>
  <p>
    <?=$this->translate('access_denied_fid_license', ['%%url%%' => $this->url('content-page', ['page' => 'Impressum'])])?>
  </p>
<?php else: ?>
  <p>
    Diese Lizenz wurde vom Fachinformationsdienst (FID) Religionswissenschaft erworben.<br>
    Die kostenfreie Nutzung der Ressource ist mit einem RelBib-Konto möglich.
  </p>


  <?php
  /**
   * The desired behaviour could not be implemented using the default lightbox attributes data-lightbox-onclose and data-lightbox-onsubmit.
   * Instead we use the following solution:
   * - custom onclick event (open the URL in a new window)
   * - data-dismiss="modal": Closes the popup AFTER the onclick event has been executed.
   */
  ?>
  <button id="licenseButton" class="btn btn-primary" data-dismiss="modal">Zum Volltext</button>
  <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$(\'#licenseButton\').click(function() { window.open(\'' . $this->licenseUrl . '\', \'_blank\')});', 'SET')?>
<?php endif; ?>
