<div class="alert alert-warning text-center" >
<h4>For maintenance reasons RelBib will not be online for a couple of hours starting at 02/17/20 09:30 CET.
</h4>
</div>
<div id="searchbox_news">
    <h2><?=$this->transEsc('RelBib News')?></h2>
    <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#01_2020"><b>Now online: Evaluation of the Survey on research data management in the study of religion</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#12_2019"><b>Have you heard of our self-archiving service?</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#07_2019"><b>Eight journals indexed in RelBib with back issues</b></a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">archive</a>
</div>
