<?php $limitList = $this->params->getLimitList();
  //In the original Vufind template, select limit and select sort are handled by different forms,
  //we check the parameters from the sort form here.
  $sortList = $this->params->getSortList();
  $sortParam = '';
  foreach($sortList as $sortName=>$sortValue) {
    if($sortValue['selected'] == 1) {
      $sortParam = $sortName;
    }
  }
?>
<?php if (count($limitList) > 1): ?>
  <form class="form-inline search-result-limit" action="<?=$this->currentPath() . $this->results->getUrlQuery()->setLimit(null)?>" method="get">
    <?=$this->results->getUrlQuery()->asHiddenFields(['sort' => '/.*/']);?>
    <label for="limit"><?=$this->transEsc('Results per page')?></label>
    <select id="limit" name="limit" class="jumpMenu form-control">
      <?php foreach ($limitList as $limitVal => $limitData): ?>
        <option value="<?=$this->escapeHtmlAttr($limitVal)?>"<?=$limitData['selected']?' selected="selected"':''?>><?=$this->escapeHtml($limitData['desc'])?></option>
      <?php endforeach; ?>
    </select>
    <noscript><input type="submit" value="<?=$this->transEscAttr("Set")?>" /></noscript>
    <?php if(!empty($sortParam)) : ?><input type="hidden" name="sort" value="<?=$sortParam;?>" /><?php endif;?>
  </form>
<?php endif; ?>
