<h2>Congresses and conferences</h2>

<h2>2023</h2>

<h3>May</h3>
<ul>
	<li>31.05-02.06.2023, Greifswald: <a target="_blank" href="https://rsf.uni-greifswald.de/storages/uni-greifswald/fakultaet/rsf/lehrstuehle/ls-harrendorf/Einladung_und_Call_for_Papers_NORDKRIM_2023.pdf">NORDKRIM 2023: Tagung des Norddeutschen Kriminologischen Gesprächskreises</a></li>
</ul>

<h3>June</h3>
<ul>
    <li>06.06.2023, Zürich (Schweiz) / ONLINE: <a target="_blank" href="https://www.team72.ch/wp-content/uploads/2017/08/resoz23_Tagungsflyer.pdf">Tagung «resoz23»: Zur Resozialisierung straffälliger Personen</a></li>
	<li>07.-09.06.2023, Berlin: <a target="_blank" href="https://2023.vse-conference.eu/">Victim Support Europe 2023 Annual Conference: ‘Protecting Fundamental Freedoms, a victim’s perspective’</a></li>
	<li>12.-13.06.2023, Mannheim: <a target="_blank" href="https://www.praeventionstag.de/nano.cms/international">Deutscher Präventionstag - Krisen & Prävention</a></li>
	<li>12.-14.06.2023, Stockholm (Sweden): <a target="_blank" href="https://criminologysymposium.com/">The Stockholm Criminology Symposium: Recognizing Knowledge to Reduce Crime and Injustice</a></li>
</ul>

<h3>July</h3>
<ul>
    <li>06.-08.07.2023, Augsburg: <a target="_blank" href="https://www.uni-augsburg.de/de/fakultaet/jura/lehrende/kaspar/kolloquium58/#:~:text=Inhalt-,Vom%206.,Gast%20und%20wird%20von%20Prof.">58. Kolloquium der Südwestdeutschen und Schweizerischen Kriminologischen Institute und Lehrstühle</a></li>
	<li>20.-21.07.2023, Lisbon (Portugal): <a target="_blank" href="https://societyforterrorismresearch.org/conferences/15th-annual-international-conference">15th Annual International Conference: Terrorism Research in a Polarized World</a></li>
</ul>

<h3>August</h3>
<ul>
    <li>30.08.-01.09.2023, Trondheim (Norway): <a target="_blank" href="https://www.iatso.org/index.php/trondheim-2022">International Association for the Treatment of Sexual Offenders (IATSO): Sex offender treatment in a lifespan perspective – New challenges from social media and from children and adolescents with harmful sexual behavior</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>6.-9.9.2023, Florence (Italy): <a target="_blank" href="https://www.esc-eurocrim.org/index.php/conferences/upcoming-conferences">EUROCRIM 2023: The 23rd Annual Conference of the European Society of Criminology</a></li>
	<li>13.-15.9.2023, Offenbach a. M.: <a target="_blank" href="http://www.fh-guestrow.de/files/dateien/forschung/call_tagung_empirische_polizeiforschung_2023.pdf">Arbeitskreis Empirische Polizeiforschung Jahrestagung 2023: Polizei und Forschung: Stillstand oder Fortschritt?</a></li>
    <li>14.-15.9.2023, Nuremberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/sexualisierte-uebergriffe-an-kindern-und-jugendlichen-umgang-und-arbeit-mit-sexualisiert-gewalttaetigen-jugendlichen-und-jungen-maennern-nuernberg-3/">Sexualisierte Übergriffe an Kindern und Jugendlichen: Umgang und Arbeit mit sexualisiert gewalttätigen Jugendlichen und jungen Männern</a></li>
    <li>15.-18.9.2023, Berlin: <a target="_blank" href="https://www.dvjj.de/veranstaltung/32-deutscher-jugendgerichtstag-2023/">DVJJ Fachtagung: 32. Deutscher Jugendgerichtstag 2023</a></li>
    <li>25.-26.9.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-ii-online/">Psychische Störungen in Haft bzw. unter StraftäterInnen II</a></li>
    <li>28.-29.9.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-ii-online/">Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten</a></li>
</ul>

<h3>October</h3>
<ul>
    <li>05.-06.10.2023, Wiesbaden: <a target="_blank" href="https://www.krimz.de/en/tagungen/conference-2023.html">KrimZ Fachtagung: Das Internet als Tatort</a></li>
</ul>

<h3>November</h3>
<ul>
    <li>03.11.2023, Berlin: <a target="_blank" href="https://protestinstitut.eu/wp-content/uploads/2022/08/CfP_2023_The-policing-of-everyday-resistance_eng.pdf">Jahrestagung des AK Soziale Bewegungen und Polizei: "Policing von Widerstand im Alltag“</a></li>
	<li>15.-18.11.2023, Philadelphia (Pennsylvania): <a target="_blank" href="https://asc41.com/#av_section_2">2023 American Society of Criminology Annual Meeting: "Seeking Justice: Reconciling with our Past, Reimagining the Future" </a></li>
</ul>


<h2>2024</h2>

<h3>September</h3>
<ul>
    <li>11.-14.09.2024, Bucharest (Romania): <a target="_blank" href="https://www.esc-eurocrim.org/index.php/conferences/upcoming-conferences">EUROCRIM 2024: 24. Annual Conference of the European Society of Criminology</a></li>
	<li>26.-28.09.2024, Tübingen: <a target="_blank" href="http://www.krimg.de/drupal/node/3"> 18. Wissenschaftliche Fachtagung der Kriminologischen Gesellschaft: „Am Puls der Zeit?! Trends, Transfer und Tradition in der Kriminologie“</a></li>
</ul>