<div class="alert alert-warning text-center" >
<h4>Aufgrund einer Systemumstellung wird RelBib am Montag, den 17.02.20 ab ca. 9:30 für einige Stunden nicht zur Verfügung stehen.</h4>
</div>
<div id="searchbox_news">
    <h2><?=$this->transEsc('RelBib News')?></h2>
    <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#01_2020"><b>Jetzt Online: Auswertung der Umfrage zu Forschungsdaten in der Religionswissenschaft</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#12_2019"><b>Schon von unserem Zweitveröffentlichungsservice gehört?</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#07_2019"><b>Acht Zeitschriften retrospektiv in RelBib nachgewiesen</b></a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">Archiv</a>
</div>
