<div id="searchbox_news">
    <div id="0" class="panel-collapse" >
        <div class="panel-body" style="text-align: justify">
        <input type="checkbox" class="read-more-state" style="border: 5px solid #000;" id="post-1" />
                    <div class="read-more-wrap">
        <p>Die in der Zeitschrift Orientalia des Päpstlichen Bibelinstituts in Rom erscheinende Internationale Keilschriftbibliographie (KeiBi) ist seit ihrer ersten Ausgabe im Jahre 1940 (Orientalia N.S. Bd. 9) zu einem unentbehrlichen Hilfsmittel für Forschung, Lehre und Studium der altorientalistischen Disziplinen geworden. Jedoch - wie in allen gedruckten, über einen längeren Zeitraum hinweg erscheinenden Bibliographien - ist die Recherche darin nicht ohne Mühe. Um dies zu erleichtern, präsentieren wir die KeiBi-Daten in Form einer Datenbank, in der alle erschienenen Ausgaben gleichzeitig durchsucht werden können.</p>
        
        <p>Ermöglicht wird der Aufbau der KeiBi-Datenbank durch die Deutsche Forschungsgemeinschaft (DFG),
        die  <div class="read-more-target">
   ihre Erstellung im Rahmen der Förderung der Virtuellen Fachbibliothek Altertumswissenschaften „Propylaeum“ unterstützt. Die KeiBi-Datenbank wird im Rahmen des Propylaeum-Moduls Alter Orient an der Universitätsbibliothek Tübingen mit Unterstützung des Instituts für die Kulturen des Alten Orients (IANES) der Universität Tübingen entwickelt.</p>
        
        <p>Die KeiBi-Daten der Ausgaben seit Ausgabe 57 (Orientalia N.S. 68, 1999) werden uns im Rahmen einer Kooperation mit dem Institut für Altorientalische Philologie und Vorderasiatische Altertumskunde der Universität Münster vom jetzigen Ersteller der Bibliographie, Prof. Dr. Hans Neumann, zur Verfügung gestellt. Die Jahrgänge davor wurden eingescannt und digital aufbereitet.i</p>
        
        <p>Aus urheberrechtlichen Gründen sind die beiden jeweils neusten Nummern nicht enthalten, d.h. beim Erscheinen einer neuen Ausgabe der KeiBi wird das vorletzte Heft hinzugefügt.</p>
        </div>
    </div>
    <label for="post-1" class="read-more-trigger" style="border-color : #888"></label>
</div>
