<?php
// Set up page title:
$this->headTitle($this->transEsc('publication_overview_headline'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('publication_overview_headline') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('authority_access_overview_headline')?></h2>
  <?php if (count($this->authorityRecords) == 0): ?>
    <p><?=$this->transEsc('authority_access_overview_empty')?></p>
  <?php else: ?>
    <table class="table">
      <tr>
        <th><?=$this->transEsc('Author')?></th>
        <th><?=$this->transEsc('Status')?></th>
      </tr>
      <?php foreach ($this->authorityUsers as $user): ?>
        <tr>
          <td><a href="/Authority/<?=urlencode($user['id'])?>"><?=$user['title']." (".$user['id'].")";?></a></td>
          <td><?=$user['access_state']?></td>
        </tr>
      <?php endforeach; ?>
    </table>

    <h2><?=$this->transEsc('publication_overview_headline')?></h2>
    <?php if (count($this->publications) == 0): ?>
      <p><?=$this->transEsc('publication_overview_empty')?></p>
    <?php else: ?>
      <table class="table">
        <tr>
          <th><?=$this->transEsc('publication_overview_column_id_external')?></th>
          <th><?=$this->transEsc('Title')?></th>
          <th><?=$this->transEsc('publication_overview_column_file_external')?></th>
          <th><?=$this->transEsc('Created')?></th>
          <th><?=$this->transEsc('publication_terms')?></th>
        </tr>
        <?php foreach ($this->publications as $publication):
          $publicationURL = ($dspaceVersion == 6) ? $this->dspaceServer."/xmlui/handle/".$publication['external_document_id'] : $this->dspaceServer."/items/".$publication['external_document_guid'];?>
          <tr>
            <td><?=$publication['external_document_id']?></td>
            <td><a href="<?=$this->recordLink()->getUrl($publication['control_number'])?>"><?=$publication['title'];?></a></td>
            <td><a href="<?=$publicationURL;?>" target="_blank"><i class="fa fa-external-link"></i> Go to file</a></td>
            <td><?=date("d.m.Y H:i:s",strtotime($publication['publication_datetime']));?></td>
            <td><a href="/publication_terms/terms_<?=date("Ymd",strtotime($publication['terms_date']));?>.pdf" target="_blank"><?=date("d.m.Y",strtotime($publication['terms_date']));?></a></td>
          </tr>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'publications'])?>
</div>
