<?php
// Set up page title:
$this->headTitle($this->translate('Admins'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Admins') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2>Admins</h2>
  <p>Additional admins must be unlocked manually in the database by the development team.</p>
  <hr />
  <table class="table dataTable">
    <thead>
      <tr>
        <th><?=$this->transEsc('Username')?></th>
        <th><?=$this->transEsc('First Name')?></th>
        <th><?=$this->transEsc('Last Name')?></th>
        <th><?=$this->transEsc('Email Address')?></th>
        <th><?=$this->transEsc('Institution')?></th>
        <th><?=$this->transEsc('Rights')?></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($this->admins as $user): ?>
        <tr>
          <td><?=htmlspecialchars($user->username)?></td>
          <td><?=htmlspecialchars($user->firstname)?></td>
          <td><?=htmlspecialchars($user->lastname)?></td>
          <td><?=htmlspecialchars($user->email)?></td>
          <td><?=htmlspecialchars($user->tuefind_institution)?></td>
          <td><?=str_replace(',', '<br>', htmlspecialchars($user->tuefind_rights))?></td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'showadmins'])?>
</div>
