<?php
$tuefind = $this->tuefind();
$currentSystem = $tuefind->getTueFindType();
$publicationEmail = $tuefind->getPublicationEmail();
$siteEmail = $tuefind->getSiteEmail();
?>

<h2>Green Road Open Access FAQ</h2>

<h3>Legal and general issues</h3>
<p>The following information was verified carefully, but it does not constitute binding legal advice. We do not assume any liability for possible errors.</p>


<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col1" aria-expanded="false" class="tf-panel-collapse-heading"><b>What can I republish?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col1">

        <p>Unfortunately, the legal situation with regards to republication is not completely clear. Different national laws may apply depending on the country of the publishing house. Furthermore, many publishing houses describe their policies and rules with regards to republication on their respective websites. You can often find these policies under headings such as “Self-Archiving” or “Open Access”. Such policies may also be found on the platform <a target="_blank" href="https://v2.sherpa.ac.uk/romeo/">Sherpa Romeo</a>.We would advise you to examine the legal situation carefully and, in case of doubt, to ask permission from the publishing house for a republication. </p>
        <p>For works or articles published by a German publishing house, <a target="_blank" href="https://www.gesetze-im-internet.de/urhg/__38.html">§38</a> of the German copyright law applies. The republication of articles from journals, anthologies and dictionaries or encyclopedias is basically allowed, but it may depend on individual agreements reached with the publisher. Monographs may not be republished unless there is an agreement to this effect (e.g. in the case of a dissertation which is out of print) with the publishing house.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col2" aria-expanded="false" class="tf-panel-collapse-heading"><b>What about contracts with a publishing house and their policies?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col2">

        <p>When a text is published for the first time, you often have a contract with the corresponding publishing house in which the right to use this publication is defined. This right determines the extent to which you may republish this work, provided it complies with the legal restrictions in place.</p>
        <p>In order to simplify this process, many publishing houses have adopted policies with specific rules for republication. You can find these policies on their websites under headings such as “Republication”, “Self-Archiving” or “Open Access”. If your publishing house has not made public any policy with regards to republication, you should ask them directly about their policy. Such policies can also be found through the platform <a target="_blank" href="https://v2.sherpa.ac.uk/romeo/">Sherpa Romeo</a>.</p>

    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col3" aria-expanded="false" class="tf-panel-collapse-heading"><b>Where does my article get republished?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col3">
        <p>When you republish a publication through <?=$currentSystem;?>, it gets stored in a repository managed by the University of Tübingen. The repository for <?=$currentSystem;?> constitutes a non-commercial subject repository. Depending on the policy of the publishing house involved in the first publication, it is possible to republish an article on one’s own personal website, on a repository belonging to one’s own institution or on a non-commercial subject repository. Commercial services such as Academia or ResearchGate are often excluded.</p>
        <p>If you are not allowed to republish your work on a non-commercial subject repository, you may be allowed to republish it in the repository of your own institution. In this case, please consult the person responsible for Open Access publications at your university library. We would appreciate it very much if you could let us know which of your publications were republished in your institutional repository so that we may include a reference to them in <?=$currentSystem;?>.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col4" aria-expanded="false" class="tf-panel-collapse-heading"><b>What about my co-author(s)?Are republication laws applicable in the case of shared authorship?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col4">
        <p>If you wrote a publication together with another or several other author(s), you need their consent before you republish it.</p>
    </div>
</div>

<div class="tf-panel-collapse">

    <p data-toggle="collapse" data-target="#col5" aria-expanded="false" class="tf-panel-collapse-heading"><b>Does my article need a cover page?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col5">
        <p>Yes, we would ask you to provide a cover page with the complete bibliographical information of the first publication of your article. This cover page should at least contain the following information:</p>
        <ul>
            <li>A note explaining that this article is being republished under the Green Open Access model</li>
            <li>Title of the article</li>
            <li>Your name as well as the name(s) of your co-author(s) (if applicable)</li>
            <li>Title of the journal or of the essay collection</li>
            <li>Editor(s) of the essay collection</li>
            <li>Place of publication</li>
            <li>Publishing house</li>
            <li>Year of publication</li>
            <li>Page numbers of the article in the original publication</li>
            <li>If applicable: permanent link (e.g. DOI, URN, Handle) to the online version or link to the website of the publishing house</li>
            <li>When a manuscript version is republished, a note explaining that the republished version has the same contents as the manuscript version, but possibly a different layout, which means that there might be differences in the page numbers.</li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col6" aria-expanded="false" class="tf-panel-collapse-heading"><b>Do I need additional image rights?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col6">
        <p>The right to use some images does not automatically apply for a republication. You should therefore verify whether you have the right to use these images again in a republication, and if not, acquire them again.</p>
        <p><a target="_blank" href="https://www.gesetze-im-internet.de/urhg/__51.html">There may be some exceptions for images from works in the public domain and for pictorial quotations according to German law</a>.</p>
        <p>If you do not have the right to use some images, they have to be removed from the publication or blackened / whitened.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col7" aria-expanded="false" class="tf-panel-collapse-heading"><b>Can my republished articles be quoted?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col7">
        <p>Yes. You can refer to your republished article by using its unique and permanent Digital Object Identifier (DOI) in a bibliographical reference. This means that your articles can be fully shared and quoted in research as well as in teaching.</p>
    </div>
</div>


<h3>Technical Procedures and Problems</h3>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col8" aria-expanded="false" class="tf-panel-collapse-heading"><b>What do I need in order to use the upload form?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col8">
        <ul>
            <li>A user account in <?=$currentSystem;?>, which you can open free of charge at this <a href="<?=$this->url('myresearch-userlogin')?>">link</a>.</li>
            <li>Access rights to your author ID, which you can gain through your <?=$currentSystem;?>-user account (see <a onclick="TueFind.goToCollapseBlock('autorID','col11')">author ID</a>).</li>
            <li>Publications which you are allowed to republish.</li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col9" aria-expanded="false" class="tf-panel-collapse-heading"><b>What is the procedure to upload the articles which I want to republish?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col9">
        <p>In order to upload a publication in <?=$currentSystem;?>, do the following:</p>
        <ol>
            <p><b>Registration</b></p>
            <li>
                <p>You need a user account in <?=$currentSystem;?>.</p>
                <p>You can register using a valid e-mail address. You can access the registration and login pop-up window by pressing on the “Login” button at the top right corner of the home page. Once you have a user account, you can proceed with the following steps.</p>
            </li>
            <p><b>Requesting Access Rights</b></p>
            <li>
                <p>Once you’ve logged into your <?=$currentSystem;?>-account, you can request access rights to your author ID. First click on the tab labelled “Persons / Corporations“ right above the search field. Search for your name and select the right entry.</p>
            </li>
            <li>
                <p>Click on the button „Request Access Rights (This is me!)”.</p>
            </li>
            <li>
                <p>Your request will be automatically sent to the <?=$currentSystem;?>-team. We will then verify your identity and inform you within a few days per e-mail whether your request has been approved.</p>
            </li>
            <p>In the next step, you can upload your essays.</p>
            <p><b>Upload (republish)</b></p>
            <li>
                <p>Once your request has been approved, log into your <?=$currentSystem;?>-account. You can now select every essay linked to you as an author for republication. When you click on the “republish” button, you can upload your essay as a PDF-file.</p>
            </li>
            <li>
                <p>Your file then gets uploaded in our repository. It should be available in Open Access to other users on the following day. At the same time, stable links (handle/DOI) to the file are generated, which you can also access on the following day. These links are permanent, and you may use them in your research and teaching activities.</p>
            </li>
        </ol>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col10" aria-expanded="false" class="tf-panel-collapse-heading"><b>What is an author ID?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col10">
        <p>An author ID is a unique and permanent identifier (a number) in the German authority file <a target="_blank" href="https://www.dnb.de/DE/Professionell/Standardisierung/GND/gnd_node.html">“Gemeinsame Normdatei” (GND)</a>, which is used by <?=$currentSystem;?> to identify you uniquely and to assign your publications to your profile.</p>
    </div>
</div>

<div id='autorID'></div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col11" aria-expanded="false" class="tf-panel-collapse-heading"><b>How do I request access rights to my author ID?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col11">
        <p>First, you go to your person information page, which you can find through the search field with the tab labelled “Persons / Corporations“ in <?=$currentSystem;?> or by clicking on the author icon near your name in the bibliographical entry for one of your works. Right above the biographical summary, you will find a button labelled <span class="save-record toolbar-btn btn-type-save"><?=$this->transEsc('authority_access_request_button')?></span>. You should then log in with your <?=$currentSystem;?>-account, if you haven’t done so yet. Your request will be automatically sent to the <?=$currentSystem;?>-team. We will then verify your identity and inform you within a few days per e-mail whether your request has been approved. Please note that you may only request access rights for your own author ID.</p>
        <p>If you have any problems, please contact us at <?=$publicationEmail;?>.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col12" aria-expanded="false" class="tf-panel-collapse-heading"><b>Why don’t I have an author ID? I can’t find my author ID.</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col12">
        <p>Please verify first whether an author ID already exists for you, for instance by searching for your name with the tab labelled “Persons / Corporations“ in <?=$currentSystem;?>. If you don’t have an author ID according to the results of this search, please contact us at <?=$publicationEmail;?>.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col13" aria-expanded="false" class="tf-panel-collapse-heading"><b>The upload-button isn’t working for my article. Why?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col13">
        <p>There are a few possible reasons for this:</p>
        <ul>
            <li><p>You haven’t logged into your user account. <a href="<?=$this->url('myresearch-userlogin')?>">Please log in</a>.</p></li>
            <li><p>You haven’t requested access rights to your <a onclick="TueFind.goToCollapseBlock('autorID','col11')">author ID</a> yet.</p></li>
            <li><p>If none of the cases listed above apply, please contact us at <?=$publicationEmail;?>.</p></li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col14" aria-expanded="false" class="tf-panel-collapse-heading"><b>I’ve already requested access rights to my author ID. Why can’t I upload my article?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col14">
        <p>The article for which you would like to upload your republished version is not linked to your author ID. The person icon which should be near your name as author of this publication is missing. <i class="fa fa-user-circle" aria-hidden="true" title=""></i> Please contact us with the link to your publication in <?=$currentSystem;?> at: <?=$publicationEmail;?>.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col15" aria-expanded="false" class="tf-panel-collapse-heading"><b>My publication is not listed.</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col15">
        <p>If you would like to upload a publication which is not already listed in <?=$currentSystem;?>, please send us the complete bibliographical information for this publication at: <?=$publicationEmail;?>.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col16" aria-expanded="false" class="tf-panel-collapse-heading"><b>I am not listed as an author of one of my publications.</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col16">
        <p>If your publication is listed in <?=$currentSystem;?>, but you do not appear as one of its authors, please contact us at <?=$publicationEmail;?>. Please send us with your e-mail the complete bibliographical information of this publication as well as a link to the corresponding entry in <?=$currentSystem;?>.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col17" aria-expanded="false" class="tf-panel-collapse-heading"><b>Which file formats may I use to upload my article?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col17">
        <p>Your publication must be in a PDF file, preferably in the PDF/A format. You can find instructions on how to produce a PDF/A file <a target="_blank" href="https://edoc-info.hu-berlin.de/de/zentral/diss_anleitungen_pdf/view">here</a>. The PDF/A format was developed to store documents in a digital archive over a long period of time. No other format (e.g. .docx, .odt, etc.) is allowed.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col18" aria-expanded="false" class="tf-panel-collapse-heading"><b>What is a persistent identifier and a stable link?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col18">
        <p>A persistent identifier or stable link is assigned to every file in order to make your republished article permanently retrievable. This link will never change, even if the file itself is moved to another storage location. This means that references to your publication using this link in our repository will always remain accurate. For this purpose, <?=$currentSystem;?> uses Digital Object Identifiers (DOI) and handles (links). Since the DOI first has to be generated, it becomes available only approx. 24 hours after the upload and appears within a few days in <?=$currentSystem;?>. </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col19" aria-expanded="false" class="tf-panel-collapse-heading"><b>When will my republished article become available online?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col19">
        <p>Your publication becomes available after it has been uploaded on the repository and can be shared through the handle/link. Our team does not verify the contents of the files nor any legal issues related to the publication. Therefore, please make sure that you upload the correct files.</p>
        <p>The Digital Object Identifier (DOI) becomes available only approx. 24 hours after the upload and appears within a few days in <?=$currentSystem;?>.</p>
    </div>
</div>


<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col20" aria-expanded="false" class="tf-panel-collapse-heading"><b>Can I change or delete my publication after it has been uploaded?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col20">
        <p>Unfortunately, a later modification or deletion of your article is not possible. Therefore, please make sure that your publication is in accordance with all copyright laws as well as exploitation, image and personal rights. Access to documents already published may be blocked on legal grounds.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col21" aria-expanded="false" class="tf-panel-collapse-heading"><b>Can I put a copy protection or a password on my publication?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col21">
        <p>Please refrain from putting any copy protection or password on your files. We follow the basic principles of Open Access, so your republished article should be available without any further obstacles.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col22" aria-expanded="false" class="tf-panel-collapse-heading"><b>What do I do if the information on my person information page is false or obsolete?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col22">
        <p>The information on your person information page is automatically obtained from various sources (e.g. GND, ORCID, etc.) and is therefore not always up-to-date. </p>
        <p>If you find any erroneous information on your page, please contact us at <?=$publicationEmail;?>.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col23" aria-expanded="false" class="tf-panel-collapse-heading"><b>My question was not properly answered / I have other questions.</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col23">
        <p>If you have any other question or concern, please contact us at: <?=$siteEmail;?>.</p>
    </div>
</div>
