<?php
$tuefind = $this->tuefind();
$currentSystem = $tuefind->getTueFindType();
$publicationEmail = $tuefind->getPublicationEmail();
$siteEmail = $tuefind->getSiteEmail();
?>

<h2>Zweitveröffentlichungsservice FAQ</h2>

<h3>Rechtliche &amp; allgemeine Fragen</h3>
<p>Die folgenden Angaben wurden sorgfältig geprüft, stellen aber keine verbindliche Rechtsberatung dar. Für mögliche Fehler kann keine Haftung übernommen werden.</p>


<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col1" aria-expanded="false" class="tf-panel-collapse-heading"><b>Was kann ich zweitveröffentlichen?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col1">
        <p>Die Rechtslage in Bezug auf Zweitveröffentlichungen ist leider nicht eindeutig. Es können abhängig vom Sitz des Verlags unterschiedliche nationale Gesetze gelten. Viele Verlage haben außerdem auf ihren jeweiligen Webseiten Policies veröffentlicht, in denen Regeln für die Zweitveröffentlichung festgelegt werden. Sie können diese Policies oft unter den Begriffen &quot;Self-Archiving&quot; oder &quot;Open Access&quot; finden. Bitte prüfen Sie die jeweilige Rechtslage und erfragen Sie im Zweifel beim jeweiligen Verlag die Erlaubnis zur Zweitveröffentlichung.</p>
        <p>Für Publikationen, die bei Verlagen mit Sitz in Deutschland erschienen sind, gilt <a target="_blank" href="https://www.gesetze-im-internet.de/urhg/__38.html">§38 Urheberrechtsgesetz</a>. Die Zweitveröffentlichung von Aufsätzen aus Zeitschriften, Sammelbänden und Lexika ist grundsätzlich möglich, aber unter Umständen abhängig von den individuell mit dem Verlag getroffenen Vereinbarungen. Monografien können nicht zweitveröffentlicht werden, sofern nicht individuelle Vereinbarungen mit dem Verlag (z. B. bei vergriffenen Dissertationsschriften) getroffen wurden.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col2" aria-expanded="false" class="tf-panel-collapse-heading"><b>Welche Rolle spielen Verlagsverträge &amp; Verlagspolicies?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col2">
        <p>Bei der Erstveröffentlichung haben Sie häufig einen Vertrag mit dem veröffentlichenden Verlag abgeschlossen, in dem die Nutzungsrechte an Ihrer Publikation geregelt sind. Diese sind für Ihre Rechte zur Zweitveröffentlichung maßgeblich, sofern die rechtlichen Vorgaben dem nicht widersprechen. </p>
        <p>Zur Vereinfachung haben viele Verlage auch Policies auf ihren Webseiten veröffentlicht, in denen sie Regeln für die Zweitveröffentlichung festlegen. Sie können diese Policies in der Regel unter den Begriffen “Zweitveröffentlichung”, “Selbstarchivierung” oder “Open Access” finden. Sollte Ihr Verlag keine Policy zur Zweitveröffentlichung veröffentlicht haben, erfragen Sie bitte die Regelungen direkt beim Verlag.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col3" aria-expanded="false" class="tf-panel-collapse-heading"><b>Wo wird mein Artikel zweitveröffentlicht?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col3">
        <p>Wenn Sie über <?=$currentSystem;?> Publikationen zweitveröffentlichen, werden diese in einem von der Universität Tübingen betriebenen Repositorium abgelegt. Das Repositorium von <?=$currentSystem;?> zählt zu den nichtkommerziell betriebenen Fachrepositorien (“non-commercial subject repository”). Zweitveröffentlichungen sind je nach Verlagspolicy auf der persönlichen Webseite, dem Repositorium der eigenen Institution oder nichtkommerziellen Fachrepositorien möglich. Kommerzielle Anbieter, wie z.B. Academia oder ResearchGate, sind häufig ausgeschlossen.</p>
        <p>Sollte die Zweitveröffentlichung auf einem nichtkommerziellen Fachrepositorium nicht gestattet sein, können Sie Ihre Publikation evtl. auf dem Repositorium Ihrer eigenen Institution zweitveröffentlichen. Bitte wenden Sie sich in diesem Fall an die Open Access-Beauftragten Ihrer Hochschulbibliothek. Teilen Sie uns gerne mit, welche Publikationen Sie in Ihrem institutionellen Repositorium zweitveröffentlicht haben, damit wir diese in <?=$currentSystem;?> nachweisen können.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col4" aria-expanded="false" class="tf-panel-collapse-heading"><b>Was ist mit meinen Ko-Autor*innen? / Gilt das Zweitveröffentlichungsrecht auch bei geteilter Autor*innenschaft?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col4">
        <p>Wenn Sie Ihre Publikationen gemeinsam mit anderen Autor*innen verfasst haben, benötigen Sie deren Einverständnis zur Zweitveröffentlichung. Bitte holen Sie deren Einverständnis vor der Zweitveröffentlichung ein.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col5" aria-expanded="false" class="tf-panel-collapse-heading"><b>Braucht meine Zweitveröffentlichung ein Deckblatt?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col5">
        <p>Bitten stellen Sie Ihrer Publikation ein Deckblatt mit den vollständigen bibliographischen Angaben der Erstveröffentlichung voran.</p>
        <p>Das Deckblatt muss mindestens die folgenden Angaben enthalten:</p>
        <ul>
            <li>Ein Hinweis, dass es sich um eine Zweitveröffentlichung im Green Open Access handelt</li>
            <li>Titel des Beitrags</li>
            <li>Ihr Name sowie die evtl. beteiligter Ko-Autor*innen</li>
            <li>Titel der Zeitschrift bzw. des Sammelwerks</li>
            <li>Herausgeber*innen bzw. beteiligte Personen des Sammelwerks</li>
            <li>Erscheinungsort</li>
            <li>Verlag</li>
            <li>Erscheinungsjahr</li>
            <li>Seitenzahlen des Beitrags in der Originalpublikation</li>
            <li>Soweit vorhanden: permanenter Link (z.B. DOI, URN, Handle) zur Online-Ausgabe oder Link zur Verlagswebseite</li>
            <li>Zweitveröffentlichungen von Manuskriptversionen müssen einen Hinweis enthalten, dass die veröffentlichte Version der Verlagsversion inhaltlich entspricht, aber nicht im Verlagslayout gesetzt ist, woraus sich Unterschiede bei der Seitenzählung ergeben können.</li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col6" aria-expanded="false" class="tf-panel-collapse-heading"><b>Benötige ich zusätzliche Bildrechte?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col6">
        <ul>
            <li>Das Recht zur Verwendung von Bildmaterial erstreckt sich nicht automatisch auf die Zweitveröffentlichung. Bitte prüfen Sie daher, ob Sie die Rechte an allen verwendeten Abbildungen auch für die Zweitveröffentlichung haben und holen sie bei Bedarf erneut ein.</li>
            <li><a target="_blank" href="https://www.gesetze-im-internet.de/urhg/__51.html">Ausnahmen können nach deutschem Recht für Abbildungen von gemeinfreien Werken und Bildzitate gelten.</a></li>
            <li>Sollten Sie keine Bildrechte erhalten, müssen die jeweiligen Bilder aus der Publikation gelöscht oder geschwärzt / geweißt werden.</li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col7" aria-expanded="false" class="tf-panel-collapse-heading"><b>Sind meine hochgeladenen Artikel zitierfähig?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col7">
        <p>Durch die Angabe des Digital Object Identifiers (DOI) in der Literaturangabe können Sie dauerhaft und eindeutig auf die verwendete Version verweisen. Damit sind Ihre Artikel in Forschung und Lehre voll zitierfähig und teilbar.</p>
    </div>
</div>

<h3>Technische Probleme und Ablauf</h3>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col8" aria-expanded="false" class="tf-panel-collapse-heading"><b>Was brauche ich für die Nutzung des Selbstupload-Formulars?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col8">
        <ul>
            <li>Ein Konto bei <?=$currentSystem;?>, das Sie <a href="<?=$this->url('myresearch-userlogin')?>">hier</a> kostenlos anlegen können</li>
            <li>Den Zugriff auf Ihre <a onclick="TueFind.goToCollapseBlock('autorID','col11')">Autor*innen-ID</a>, die Sie mit Ihrem <?=$currentSystem;?>-Konto beansprucht haben</li>
            <li>Publikationen, die Sie zweitveröffentlichen dürfen </li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col9" aria-expanded="false" class="tf-panel-collapse-heading"><b>Wie funktioniert der Selbstupload meiner Zweitveröffentlichungen?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col9">
        <p>Um eine Publikation auf <?=$currentSystem;?> hochzuladen, gehen Sie wie folgt vor:</p>
        <ol>
            <p><b>Registrierung</b></p>
            <li>
                <p>Sie benötigen einen <?=$currentSystem;?>-Account.</p>
                <p>Dafür müssen Sie sich lediglich einmalig mit einer gültigen E-Mail-Adresse registrieren. Den Link zur Registrierung und zum Login finden Sie auf der Startseite rechts oben unter dem Button &quot;Login&quot;. Sobald Sie einen <?=$currentSystem;?>-Account haben, können Sie mit den weiteren Schritten fortfahren.</p>
            </li>
            <p><b>Rechte beantragen</b></p>
            <li>
                <p>Sobald Sie in Ihrem <?=$currentSystem;?> Konto angemeldet sind, können Sie den Zugriff auf Ihre Autor*innen-ID beantragen. Dazu wählen Sie den Reiter &quot;Personen/Körperschaften&quot; oberhalb des Suchschlitzes. Suchen Sie nach Ihrem Namen und wählen Sie den richtigen Eintrag aus.</p>
            </li>
            <li>
                <p>Klicken Sie auf den Button &quot;Request Access Rights (This is me!)&quot;</p>
            </li>
            <li>
                <p>Ihre Anfrage wird nun automatisch an das <?=$currentSystem;?>-Team geschickt. Wir überprüfen, ob Sie die genannte Person sind, und informieren Sie innerhalb weniger Tage per E-Mail, ob Ihr Antrag genehmigt wurde.</p>
                <p>Nun können Sie im nächsten Schritt Ihre Publikationen hochladen.</p>
            </li>
            <p><b>Upload (republish)</b></p>
            <li>
                <p>Sobald Ihr Antrag genehmigt wurde, melden Sie sich erneut in Ihrem <?=$currentSystem;?>-Konto an. Nun können Sie jeden Aufsatz für eine Zweitveröffentlichung auswählen, der mit Ihnen als Autor*in verknüpft ist. Wenn Sie auf den Button &quot;republish&quot; klicken, können Sie ein Digitalisat Ihrer Publikation als PDF-Datei hochladen.</p>
            </li>
            <li>
                <p>Im Anschluss wird Ihre Datei auf das Repositorium hochgeladen. Im Regelfall steht sie ab dem folgenden Tag für andere Nutzer*innen im Open Access zur Verfügung. Gleichzeitig werden stabile Links (handle/doi) generiert, die Sie ebenfalls ab dem folgenden Tag abrufen können. Diese Links bleiben dauerhaft erhalten und können von Ihnen für Forschung und Lehre verwendet werden.</p>
            </li>
        </ol>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col10" aria-expanded="false" class="tf-panel-collapse-heading"><b>Was ist eine Autor*innen-ID?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col10">
        <p>Eine Autor*innen-ID ist eine eindeutige und stabile Nummer in der <a target="_blank" href="https://www.dnb.de/DE/Professionell/Standardisierung/GND/gnd_node.html">Gemeinsamen Normdatenbank (GND)</a>, die von <?=$currentSystem;?> nachgenutzt wird, um Sie als Autor*in eindeutig zu identifizieren und Ihre Publikationen zuordnen zu können.</p>
    </div>
</div>
<div id='autorID'></div>
<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col11" aria-expanded="false" class="tf-panel-collapse-heading"><b>Wie beantrage ich den Zugriff auf meine Autor*innen-ID?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col11">
        <ul>
            <li>Gehen Sie zunächst auf Ihre Personenseite, bspw. über die Personensuche von <?=$currentSystem;?> oder einen Klick auf die Autorenanzeige neben Ihrem Namen bei einem Aufsatz. Am oberen Rand der Übersicht finden Sie den Button <span class="save-record toolbar-btn btn-type-save"><?=$this->transEsc('authority_access_request_button')?></span>. Bitte loggen Sie sich hier in Ihr <?=$currentSystem;?>-Konto ein, sofern noch nicht geschehen. Ihre Anfrage wird nun automatisch an das <?=$currentSystem;?>-Team geschickt. Wir überprüfen, ob Sie die genannte Person sind, und informieren Sie innerhalb weniger Tage per E-Mail, ob Ihr Antrag genehmigt wurde.</li>
            <li>Bitte beachten Sie, dass pro <?=$currentSystem;?>-Konto nur die Rechte für eine Autor*innen-ID vergeben werden können. Ebenso kann eine Autor*innen-ID nur von einem Konto beansprucht werden.</li>
            <li>Bei Problemen wenden Sie sich bitte an: <?=$publicationEmail;?>.</li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col12" aria-expanded="false" class="tf-panel-collapse-heading"><b>Warum habe ich keine Autor*innen-ID? /  Ich finde meine Autor*innen-ID nicht.</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col12">
        <p>Bitte prüfen Sie zunächst, ob für Ihre Person bereits eine Autor*innen-ID existiert, etwa durch eine Suche nach Ihrem Namen im Reiter &quot;Personen/Körperschaften&quot; in <?=$currentSystem;?>. Sollte diese Suche ergeben, dass Sie noch keine Autor*innen-ID haben, nehmen Sie gerne Kontakt zu uns auf: <?=$publicationEmail;?>.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col13" aria-expanded="false" class="tf-panel-collapse-heading"><b>Warum funktioniert der Button für den Upload meines Artikels nicht?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col13">
        <p>Hierfür kann es mehrere Gründe geben:</p>
        <ul>
            <li>Sie sind nicht eingeloggt. Bitte loggen Sie sich <a href="<?=$this->url('myresearch-userlogin')?>">hier</a> ein.</li>
            <li>Sie haben den Zugriff auf Ihre <a onclick="TueFind.goToCollapseBlock('autorID','col11')">Autor*innen-ID</a> noch nicht beantragt.</li>
            <li>Falls keiner der genannten Punkte das Problem löst, wenden Sie sich bitte an uns <?=$publicationEmail;?>.</li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col14" aria-expanded="false" class="tf-panel-collapse-heading"><b>Ich habe bereits den Zugriff auf meine Autor*innen-ID beantragt. Warum kann ich meinen Artikel nicht hochladen?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col14">
        <p>Die Publikation, die Sie hochladen möchten, ist nicht mit Ihrer Autor*innen-ID verknüpft. Das Personen-Icon hinter Ihrem Namen in der Autor*innenangabe des Beitrags fehlt. <i class="fa fa-user-circle" aria-hidden="true" title=""></i> Wenden Sie sich in diesem Fall bitte mit dem Link zu Ihrer Publikation in <?=$currentSystem;?> an uns: <?=$publicationEmail;?>.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col15" aria-expanded="false" class="tf-panel-collapse-heading"><b>Meine Publikation ist nicht verzeichnet.</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col15">
        <p>Wenn Sie Publikationen hochladen möchten, die noch nicht in <?=$currentSystem;?> verzeichnet sind, wenden Sie sich bitte mit der vollständigen bibliographischen Angabe an uns: <?=$publicationEmail;?>.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col16" aria-expanded="false" class="tf-panel-collapse-heading"><b>Ich bin im Eintrag einer meiner Publikationen nicht als Autor*in aufgeführt.</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col16">
        <p>Falls Ihre Publikation in <?=$currentSystem;?> auffindbar ist, Sie aber nicht als Autor*in verzeichnet sind, wenden Sie sich bitte an uns <?=$publicationEmail;?>. Bitte fügen Sie Ihrer Mail die vollständige bibliografische Angabe sowie den Link zu der Publikation in <?=$currentSystem;?> bei.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col17" aria-expanded="false" class="tf-panel-collapse-heading"><b>In welchem Dateiformat kann ich meine Publikation hochladen?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col17">
        <p>Ihre Publikation muss im PDF-Format hochgeladen werden, wenn möglich im PDF/A-Format. Eine Anleitung zur Erstellung einer PDF/A-Datei finden Sie z.B. <a target="_blank" href="https://edoc-info.hu-berlin.de/de/zentral/diss_anleitungen_pdf/view">hier</a>. Das PDF/A-Format wurde für die Langzeitarchivierung von Dokumenten entwickelt. Der Upload in anderen Formaten (z.B. .docx, .odt, etc.) ist nicht möglich.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col18" aria-expanded="false" class="tf-panel-collapse-heading"><b>Was sind persistente Identifier und stabile Links?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col18">
        <p>Um die Wiederauffindbarkeit Ihrer Zweitveröffentlichung zu gewährleisten, wird jeder Datei ein persistenter Identifier bzw. stabiler Link zugeordnet. Dieser Link wird sich nicht verändern, auch wenn sich der Speicherort der Datei verändert. Dadurch ist Ihre Publikation im Repositorium dauerhaft zitierfähig. Für <?=$currentSystem;?> werden Digital Object Identifier (DOI) und Handle-Links genutzt. Da der DOI erst erzeugt werden muss, steht der DOI ca. 24 Stunden nach dem Upload zur Verfügung und erscheint innerhalb weniger Tage in <?=$currentSystem;?>. Nachdem der DOI erzeugt wurde, erhalten Sie von uns eine Mail.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col19" aria-expanded="false" class="tf-panel-collapse-heading"><b>Wann ist meine zweitveröffentlichte Publikation online verfügbar?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col19">
        <ul>
            <li>Ihre Publikation ist nach dem Upload auf dem Repositorium verfügbar und ist über den Handle-Link teilbar. Eine rechtliche oder inhaltliche Prüfung durch unser Team erfolgt nicht. Bitte achten Sie daher darauf, die korrekten Dateien hochzuladen.</li>
            <li>Der Digital Object Identifier (DOI) steht erst nach ca. 24 Stunden zur Verfügung und erscheint nach wenigen Tagen in <?=$currentSystem;?>.</li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col20" aria-expanded="false" class="tf-panel-collapse-heading"><b>Kann ich meine hochgeladene Publikation nachträglich selbst ändern oder löschen?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col20">
        <p>Eine nachträgliche Änderung oder Löschung Ihres Beitrags ist leider nicht möglich. Bitte achten Sie deshalb im Vorfeld auf die Einhaltung von Urheber-, Verwertungs-, Bild- und Persönlichkeitsrechten. Aus rechtlichen Gründen kann der Zugriff auf bereits veröffentlichte Dokumente gesperrt werden.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col21" aria-expanded="false" class="tf-panel-collapse-heading"><b>Kann ich meine Publikation mit einem Kopierschutz oder Passwort versehen?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col21">
        <p>Bitte verzichten Sie darauf, Ihre Dateien mit Kopier- oder Passwortschutz zu versehen. Dem Grundgedanken des Open Access folgend sollen zweitveröffentlichte Publikationen ohne weitere Hürden zugänglich sein.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col22" aria-expanded="false" class="tf-panel-collapse-heading"><b>Was mache ich bei falschen oder veralteten Angaben auf meiner Personenseite?</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col22">
        <ul>
            <li>Die Angaben auf Ihrer Personenseite werden automatisiert aus verschiedenen Quellen (z.B. GND, ORCID, etc.) zusammengestellt und sind daher nicht immer aktuell.</li>
            <li>Sollten Ihnen Fehler auffallen, wenden Sie sich bitte an <?=$publicationEmail;?>.</li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <p data-toggle="collapse" data-target="#col23" aria-expanded="false" class="tf-panel-collapse-heading"><b>Meine Frage wurde nicht beantwortet / Ich habe weitere Fragen.</b></p>
    <div class="collapse multi-collapse tf-panel-collapse-body" id="col23">
        <p>Haben Sie noch weitere Fragen oder Anliegen? Wenden Sie sich gerne an: <?=$siteEmail;?></p>
    </div>
</div>
